login:
  path: /login
  controller: App\Controller\SecurityController::login

logout:
  path: /logout  
  controller: App\Controller\SecurityController::logout

register:
  path: /register  
  controller: App\Controller\SecurityController::register

activation_user:
  path: /user/{token}   
  controller: App\Controller\SecurityController::activationUser 


forget_password:
  path: /forgetpassword
  controller: App\Controller\SecurityController::forgetPassword  


reset_password:
  path: /resetpassword/{token}
  controller: App\Controller\SecurityController::resetPassword  



  
