resources:
    App\Entity\Ad:
        attributes:
            normalization_context:
                groups: ['read_ad']
            denormalization_context:
                groups: ['write_ad']
        collectionOperations:
            get:
                filters: ['customsearch.ad_filter' ,'customsearch.date_filter' ,'searchad.price_filter' , 'searchad.gov_filter' ]
            post: ~    
        itemOperations: ~    
                
         
    App\Entity\Bouking:
        attributes:
            normalization_context:
                groups: ['read_bk']
            denormalization_context:
                groups: ['write_bk']
        collectionOperations: ~
        itemOperations: ~ 


    App\Entity\User:
        attributes:
            normalization_context:
                groups: ['read_user']
            denormalization_context:
                groups: ['write_user']
        collectionOperations:
            get:
                filters: ['searchUser.filter' ]
            post: ~    
        itemOperations: ~  

        
         
    App\Entity\Image:
        attributes:
            normalization_context:
                    groups: ['read_img']
            denormalization_context:
                    groups: ['write_img']
            collectionOperations:
                get:  ~ 
                   
                post: ~    
            itemOperations: ~  


    App\Entity\Rating: ~
    App\Entity\Search: ~
    App\Entity\Role: ~







    # App\Entity\Offer:
    #     shortName: 'Offer'                   
    #     description: 'An offer from my shop' 
    #     iri: 'http://schema.org/Offer'       
    #     attributes:                          
    #         pagination_items_per_page: 25    